import type { Menu } from "@/components/menu/menu.vue";

export const OAT_MILK = "Oat Milk";

export const MENU: Menu = {
  Bingsu: [
    {
      price: 25.5,
      priceSmall: 18.5,
      name: "Roasted Soybean Oolong",
      imageName: "roasted-soybean-oolong",
      recommendedToppings: [
        "Soybean Mochi Cubes",
        "Brown Sugar Jelly",
        "Butter Crisp",
        "Cream Cheese with Soybean Powder",
      ],
    },
    {
      price: 24,
      priceSmall: 18,
      name: "White Peach Oolong",
      imageName: "white-peach-oolong",
      recommendedToppings: ["Brown Sugar Jelly", "Peach Popping Boba", "Taroball"],
    },
    {
      price: 28,
      priceSmall: 20,
      name: "Mango Sago",
      imageName: "mango",
      recommendedToppings: ["Nata De Coco", "Passionfruit Popping Boba", "Mango Sauce", "Mango"],
    },
    {
      price: 27,
      priceSmall: 19,
      name: "Thai Milk Tea",
      imageName: "thai-milk-tea",
      recommendedToppings: ["Water Chestnut Popping Boba", "Ondeh-Ondeh Mochi", "Lotus Biscoff Crumbs"],
    },
    {
      price: 35,
      priceSmall: 25,
      name: "Pistachio",
      imageName: "pistachio",
      recommendedToppings: ["Chocolate Butter Crisp", "White Sugar Jelly", "Glazed Pistachio Crumbs"],
    },
    {
      price: 27,
      priceSmall: 19,
      name: "Dark Chocolate",
      imageName: "the-dark-knight",
      recommendedToppings: ["Butter Crisp", "Dark Chocolate Mochi Cubes", "White Sugar Jelly"],
    },
    {
      price: 29,
      priceSmall: 21,
      name: "Matcha",
      imageName: "matcha",
      recommendedToppings: ["Brown Sugar Jelly", "Red Bean", "Soybean Mochi Cubes", "Cream Cheese Only"],
    },
    {
      price: 29,
      priceSmall: 21,
      name: "Hoji Cha Cha",
      imageName: "hoji-cha-cha",
      recommendedToppings: ["Brown Sugar Jelly", "Red Bean", "Soybean Mochi Cubes", "Cream Cheese Only"],
    },
    {
      price: 24,
      priceSmall: 18,
      name: "Kumquat Jasmine",
      imageName: "kumquat-jasmine",
      recommendedToppings: ["Nata De Coco", "Passionfruit Popping Boba", "Aiyu Jelly"],
    },
    {
      price: 29,
      priceSmall: 20.5,
      name: "Tiramisu",
      imageName: "tiramisu",
      recommendedToppings: ["Brown Sugar Jelly", "Chocolate Butter Crisp", "Mascarpone Cream"],
    },
    {
      price: 26,
      priceSmall: 18.5,
      name: "Soybean Longan",
      imageName: "soybean-longan",
      recommendedToppings: ["Brown Sugar Jelly", "Water Chestnut Popping Boba", "Longan"],
    },
    {
      // No small size available for this item yet
      price: 30,
      name: "Matcha Crème Brulee",
      imageName: "matcha-creme-brulee",
      recommendedToppings: ["Brown Sugar Jelly", "Soybean Mochi Cubes", "Red Bean", "Crème Brulee Cream Cheese"],
    },
    {
      // No small size available for this item yet
      price: 30,
      name: "Dark Chocolate Pistachio Kunafa",
      imageName: "dark-chocolate-pistachio-kunafa",
      recommendedToppings: ["White Sugar Jelly", "Dark Chocolate Mochi Cubes", "Pistachio Kunafa"],
    },
  ],
  Drinks: [
    {
      price: 14,
      name: "Da Hong Pao Roasted Milk Tea",
      imageName: "roasted-da-hong-pao-milk-tea",
      description: "Our TOP 1 drink — a comforting roasted milk tea with cream cheese and crystal jelly",
    },
    {
      price: 16,
      name: "Signature Binq Tea",
      imageName: "signature-binq-tea",
      description: "Our TOP 2 signature — jasmine tea with watermelon cube, mango cube, and crystal jelly",
    },
    {
      price: 16,
      name: "Watermelon Cheezo",
      imageName: "watermelon-cheezo",
      description: "Refreshing watermelon with jasmine tea, watermelon cube, and crystal jelly",
    },
    {
      price: 16,
      name: "Lychee Cheezo",
      imageName: "lychee-cheezo",
      description: "Exotic sweetness of lychee with jasmine tea, lychee cube, and crystal jelly",
    },
    {
      price: 9,
      name: "Chamomile Tea",
      imageName: "chamomile-tea",
      description: "Hot — gentle and floral. A calming cup to end your meal",
    },
    {
      price: 9,
      name: "Pure Green Tea",
      imageName: "green-tea",
      description: "Hot — classic and light. Clean and refreshing",
    },
    {
      price: 9,
      name: "English Breakfast Tea",
      imageName: "english-breakfast-tea",
      description: "Hot — full-bodied and robust. Perfect with or without milk",
    },
  ],
  Topping: [
    {
      price: 3,
      name: "Soybean Mochi Cubes",
      imageName: "soybean-mochi-cube",
      description: "The difference in chewy profile cannot be compared when coated with soybean",
    },
    {
      price: 3,
      name: "Dark Chocolate Mochi Cubes",
      imageName: "dark-chocolate-mochi-cube",
      description: "Rich dark chocolate coating with a satisfying mochi chew",
    },
    {
      price: 3,
      name: "Ondeh-Ondeh Mochi",
      imageName: "ondeh-ondeh-mochi",
      description: "Gula melaka filled glutinous squares with a coconutty finish",
    },
    {
      price: 4,
      name: "Taroball",
      imageName: "taroballs",
      description: "Chewy taro balls that add a comforting and nostalgic touch",
    },
    {
      price: 2,
      name: "Brown Sugar Jelly",
      imageName: "brown-sugar-crystal-jelly",
      description: "Rich caramel flavor with a jelly-like texture",
    },
    {
      price: 2,
      name: "White Sugar Jelly",
      imageName: "white-crystal-jelly",
      description: "Add a burst of sweetness to your bingsu with this topping",
    },
    {
      price: 2,
      name: "Water Chestnut Popping Boba",
      imageName: "waterchestnut-popping-boba",
      description: "Unique texture and subtle sweetness in every pop",
    },
    {
      price: 2,
      name: "Nata De Coco",
      imageName: "nata-de-coco",
      description: "Chewy texture and refreshing taste — perfect for a tropical twist",
    },
    {
      price: 3,
      name: "Peach Popping Boba",
      imageName: "peach-popping-boba",
      description: "Bursting with juicy peach flavor with every pop",
    },
    {
      price: 3,
      name: "Lychee Popping Boba",
      imageName: "lychee-popping-boba",
      description: "Popping sweet lychee — it can't get better than this",
    },
    {
      price: 2,
      name: "Passionfruit Popping Boba",
      imageName: "passionfruit-popping-boba",
      description: "Delivering a burst of tangy passionfruit goodness",
    },
    {
      price: 3,
      name: "Aiyu Jelly",
      imageName: "aiyu-jelly",
      description: "Translucent jelly with a delicate flavor that complements your bingsu perfectly",
    },
    {
      price: 2,
      name: "Mango",
      imageName: "mango",
      description: "Delight in the sweetness of ripe mango",
    },
    {
      price: 2,
      name: "Red Bean",
      imageName: "red-bean",
      description: "A classic and comforting taste — pairs perfectly with any bingsu",
    },
    {
      price: 2,
      name: "Butter Crisp",
      imageName: "butter-crisp",
      description: "Add a crunchy and buttery twist to your bingsu",
    },
    {
      price: 3,
      name: "Chocolate Butter Crisp",
      imageName: "chocolate-butter-crisp",
      description: "Our classic butter crisp, dipped in chocolate",
    },
    {
      price: 3,
      name: "Lotus Biscoff Crumbs",
      imageName: "lotus-biscoff",
      description: "A crunch, plus a caramelised touch to your bingsu",
    },
    {
      price: 5,
      name: "Glazed Pistachio Crumbs",
      imageName: "glazed-pistachio-crumbs",
      description: "Real crushed pistachio nuts with a light glaze",
    },
    {
      price: 3.5,
      name: "Cream Cheese Only",
      imageName: "cream-cheese",
      description: "Adds richness and flavor to every bite — just pour it over",
    },
    {
      price: 3.5,
      name: "Cream Cheese with Soybean Powder",
      imageName: "cream-cheese",
      description: "Cheese and soybean powder — creating multiple indulgent layers",
    },
    {
      price: 3,
      name: "Mascarpone Cream",
      imageName: "mascarpone-cream",
      description: "Silky Italian cream cheese, mild and luxuriously smooth",
    },
    {
      price: 4,
      name: "Longan",
      imageName: "longan",
      description: "Sweet, fragrant longan for a refreshing finish",
    },
    {
      price: 4,
      name: "Crème Brulee Cream Cheese",
      imageName: "creme-brulee-cream-cheese",
      description: "Our cream cheese, finished with a caramelised crème brûlée touch",
    },
    {
      price: 5,
      name: "Pistachio Kunafa",
      imageName: "pistachio-kunafa",
      description: "Crispy kunafa pastry threads tossed with pistachio",
    },
    {
      price: 3.5,
      name: "Mango Sauce",
      imageName: "mango-sauce",
      description: "A bright, fruity mango sauce drizzled over your bingsu",
    },
  ],
  "Dubai Chewy Cookie": [
    {
      price: 13,
      name: "Big Dubai Chewy Cookie (1pc)",
      imageName: "big-dubai-chewy-cookie",
      description: "A single big, gooey Dubai-style chewy cookie with a chocolate pistachio kunafa filling",
    },
    {
      price: 25,
      name: "Big Dubai Chewy Cookie (2pcs)",
      imageName: "big-dubai-chewy-cookie",
      description: "Two big, gooey Dubai-style chewy cookies with a chocolate pistachio kunafa filling",
    },
    {
      price: 36,
      name: "Big Dubai Chewy Cookie (3pcs)",
      imageName: "big-dubai-chewy-cookie",
      description: "Three big, gooey Dubai-style chewy cookies with a chocolate pistachio kunafa filling",
    },
    {
      price: 13,
      name: "Mini Dubai Chewy Cookie (3pcs)",
      imageName: "mini-dubai-chewy-cookie",
      description: "Three bite-sized Dubai-style chewy cookies, perfect for sharing",
    },
    {
      price: 25,
      name: "Mini Dubai Chewy Cookie (6pcs)",
      imageName: "mini-dubai-chewy-cookie",
      description: "Six bite-sized Dubai-style chewy cookies, perfect for sharing",
    },
    {
      price: 36,
      name: "Mini Dubai Chewy Cookie (9pcs)",
      imageName: "mini-dubai-chewy-cookie",
      description: "Nine bite-sized Dubai-style chewy cookies, perfect for sharing",
    },
    {
      price: 45,
      name: "Mini Dubai Chewy Cookie Gift Box (12pcs)",
      imageName: "mini-dubai-chewy-cookie-gift-box",
      description: "A 12-piece gift box of our mini Dubai-style chewy cookies",
    },
    {
      price: 80,
      name: "Mini Dubai Chewy Cookie Gift Box (24pcs)",
      imageName: "mini-dubai-chewy-cookie-gift-box",
      description: "A 24-piece gift box of our mini Dubai-style chewy cookies",
    },
  ],
  Croffle: [
    {
      price: 14,
      name: "Croffle with Sauce",
      imageName: "croffle-with-sauce",
      description: "Crispy croissant-waffle hybrid, served with your choice of sauce",
    },
    {
      price: 11,
      name: "Croffle With No Sauce",
      imageName: "croffle-no-sauce",
      description: "Crispy croissant-waffle hybrid, plain. Only available with a Bingsu purchase",
    },
  ],
  "Iced Chocolate": [
    {
      price: 16,
      name: "Iced Chocolate",
      imageName: "iced-chocolate",
      description: "Rich and chocolatey, served over ice",
    },
    {
      price: 16,
      name: "Mocha Cloud",
      imageName: "mocha-cloud",
      description: "Chocolate and coffee, topped with a cloud of cream",
    },
    {
      price: 16,
      name: "Cheese Cloud",
      imageName: "cheese-cloud",
      description: "Our iced chocolate, topped with a cloud of cream cheese foam",
    },
    {
      price: 15,
      name: "Hot Chocolate",
      imageName: "hot-chocolate",
      description: "Rich and chocolatey, served warm",
    },
  ],
};
