name: Build and Deploy Binq Static Web
run-name: Building and Deployiing
on:
  pull_request:
    branches:
      - "dev"
      - "master"
      - "!feature-**/"

env:
  NODE_VERSION: "20.10.0"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Attempting to install required tools and build project"
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Install Dependencies and Build project
        run: |
          npm ci
          npm run build

      - run: echo "🍏 This job's status is ${{ job.status }}."
