name: Build and Deploy Binq Static Web
run-name: Building and Deployiing
on:
  pull_request:
    branches:
      - "dev"
      - "master"
      - "!feature-**/"

env:
  NODE_VERSION: "20.10.0"
  ARTIFACT_RETENTION_DAYS: 90

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Attempting to install required tools and build project"
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Install Dependencies and Build project
        run: |
          npm ci
          npx tailwindcss build -i ./src/input.css -o ./src/output.css --minify
          npm run build --f-present

      - name: Store production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifact_${{ github.event.repository.updated_at}}
          path: |
            dist
            !dist/**/*.md
          retention-days: ${{ env.ARTIFACT_RETENTION_DAYS }}

      - run: echo "🍏 This job's status is ${{ job.status }}."
